#? ?? ?? ?? ??
server:
  port: 80

#?????? ?? ??
spring:
  datasource:
    url: jdbc:mysql://choongangmysql.cesn3uejbkwe.ap-northeast-2.rds.amazonaws.com:3306/adam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: choongang1025!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #??? ???? ???? ??? ???? ??
  logging:
    level:
      org.hibernate.type.descriptor.sql: trace

  kafka:
    bootstrap-servers: 43.201.249.166:9092
    consumer:
      group-id: adamsoft
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
